### ISSUE TITLE
Error confirm without selection in 'msetup"

### ISSUE THREAD

**Issue by Zowder** [latarc/umbu#10]
## Expected Behavior

When the user does not select any option, you must return to the CLI of the UMBU and communicate a message.
## Current Behavior

There is not this type of verification.
## Possible Solution

- [x] Create a mechanism to check if the user selection is empty.
- [x] If it is empty, treat the exception and re-draw umbu cli.

**Comment by carlosbda99** [comment]
Bug fixed in commit 2ff120ef16f2026c4f690ed2348a42557c3d17a4
