### ISSUE TITLE
Verification of projects already prepared

### ISSUE THREAD

**Issue by Zowder** [latarc/umbu#5]
## Expected Behavior

When the user wants to prepare a previous project, the folder must be cleaned before the new preparation can happen without problems.

## Current Behavior

Running the command msetup in a project that was previously prepared, ffmpeg will ask if you want to overwrite the files, but this message does not appear in the prompt of the umbu, this way it prevents the interaction between the user and the CLI of the UMBU and consequently, the project is not being prepared again.

## Possible Solution

- [x] Ask the user if he wants to clean the directory to a new preparation of video.
- [x] Check if there is any video before proceeding.
- [x] Treat error check without selecting any entry.

**Comment by carlosbda99** [comment]
Bug fixed on commit 7210dc78dd2c8e0cf4ed0cad2035171fe94c436f
