### ISSUE TITLE
Error when the client connects to the server before

### ISSUE THREAD

**Issue by Zowder** [latarc/umbu#6]
## Expected Behavior

The UMBU should not close the CLI when the client attempts to connect to a server that is not with the socket connection to active.

## Current Behavior

When a client tries to connect to a server UMBU who is not with the socket connection to active, the client displays an error and closes the CLI.

## Possible Solution

- [x] - In the socket, filter the messages of connection error.
- [x] - Keep the CLI even when the connection cannot be established.

**Comment by carlosbda99** [comment]
2ff120ef16f2026c4f690ed2348a42557c3d17a4
