### ISSUE TITLE
Check if there is something to send in the "sender exp"

### ISSUE THREAD

**Issue by Zowder** [latarc/umbu#8]
## Expected Behavior

should check to see if there are any pre-prepared project to be sent.
## Current Behavior

There is not this type of verification.
## Possible Solution

- [ ] Create a mechanism to check if there is any project to be sent, if not, tell the user before proceeding, if any, list the options normally.

**Comment by carlosbda99** [comment]
2ff120ef16f2026c4f690ed2348a42557c3d17a4

**Comment by carlosbda99** [comment]
Bug fixed in commit 2ff120ef16f2026c4f690ed2348a42557c3d17a4
